
// fern
NF('fern').set(\lfnFreq, 1.27, \repeats, 1.0, \freqMult, 0.585, \freqMult2, 0.103, \knumFrom, 1000.0, \knumTo, 1.34, \ampStep, 0.804, \stiffness, 0.167, \ampStepB, 1.0, \stiffnessB, 0.047, \harmScale, 0.041, \detuneHi, 0.218, \detuneLo, 0.1278, \templateType, 1.0, \ampDistParam, 1.0, \seqMode, 3.0, \factorsMult, 0.303, \amp, 0.857);
NF('fern').set(\ampStep, 0.602, \stiffness, 0.415, \stiffnessB, 0.985, \freqMult, 0.988, \detuneLo, 0.5291, \harmScale, 0.056, \lfnFreq, 0.05, \detuneHi, 2.362, \amp, 0.612, \repeats, 9.0, \ampStepB, 0.289);
NF('fern').set(\lfnFreq, 0.83, \repeats, 3.0, \freqMult, 1.192, \freqMult2, 0.103, \knumFrom, 1000.0, \knumTo, 1.34, \ampStep, 0.025, \stiffness, 0.152, \ampStepB, 0.021, \stiffnessB, 0.017, \harmScale, 0.025, \detuneHi, 0.345, \detuneLo, 0.2366, \templateType, 1.0, \ampDistParam, 1.0, \seqMode, 3.0, \factorsMult, 0.303, \amp, 0.898);
NF('fern').set(\lfnFreq, 0.05, \repeats, 5.0, \freqMult, 0.311, \freqMult2, 0.23, \knumFrom, 1000.0, \knumTo, 197.27, \ampStep, 0.655, \stiffness, 1.0, \ampStepB, 1.0, \stiffnessB, 0.502, \harmScale, 0.033, \detuneHi, 0.371, \detuneLo, 0.1016, \templateType, 2.0, \ampDistParam, 0.066, \seqMode, 3.0, \factorsMult, 7.116, \amp, 0.857);
NF('fern').set(\lfnFreq, 40.0, \repeats, 2.0, \freqMult, 1.06, \freqMult2, 0.123, \knumFrom, 1.0, \knumTo, 3.72, \ampStep, 0.689, \stiffness, 0.077, \ampStepB, 0.289, \stiffnessB, 0.399, \harmScale, 0.049, \detuneHi, 0.052, \detuneLo, 0.0163, \templateType, 1.0, \ampDistParam, 0.247, \seqMode, 1.0, \factorsMult, 0.133, \amp, 0.612);
NF('fern').set(\lfnFreq, 9.9, \repeats, 3.0, \freqMult, 0.769, \freqMult2, 1.405, \knumFrom, 1.0, \knumTo, 13.12, \ampStep, 0.745, \stiffness, 0.381, \ampStepB, 0.289, \stiffnessB, 0.783, \harmScale, 0.024, \detuneHi, 1.15, \detuneLo, 0.5388, \templateType, 1.0, \ampDistParam, 0.608, \seqMode, 1.0, \factorsMult, 0.101, \amp, 0.612);
NF('fern').set(\lfnFreq, 0.83, \repeats, 1.0, \freqMult, 4.074, \freqMult2, 0.103, \knumFrom, 1000.0, \knumTo, 1.34, \ampStep, 0.025, \stiffness, 0.152, \ampStepB, 0.021, \stiffnessB, 0.017, \harmScale, 0.025, \detuneHi, 0.345, \detuneLo, 0.2366, \templateType, 1.0, \ampDistParam, 1.0, \seqMode, 3.0, \factorsMult, 0.303, \amp, 0.898);
NF('fern').set(\lfnFreq, 40.0, \repeats, 1.0, \freqMult, 1.983, \freqMult2, 0.103, \knumFrom, 553.89, \knumTo, 1000.0, \ampStep, 0.0, \stiffness, 0.152, \ampStepB, 0.057, \stiffnessB, 0.721, \harmScale, 0.022, \detuneHi, 0.345, \detuneLo, 0.2366, \templateType, 1.0, \ampDistParam, 1.0, \seqMode, 3.0, \factorsMult, 0.303, \amp, 0.898);

// moss
NF('moss').set(\lfnFreq, 0.03, \mod, 24.41, \from, 1.43, \to, 2.24, \freqFrom, 13.12, \freqTo, 210.66, \jitter, 0.902, \ampStep, 0.412, \duty, 0.073, \hpf, 191.21, \sdm, 1.79, \grainGain, 0.667, \knum, 18.08, \factorsMult, 0.577, \amp, 0.192);
NF('moss').set(\lfnFreq, 0.04, \mod, 19.64, \from, 40.0, \to, 9.37, \freqFrom, 500.0, \freqTo, 516.74, \jitter, 0.681, \ampStep, 0.102, \duty, 0.103, \hpf, 21.3, \sdm, 19.83, \grainGain, 0.112, \knum, 17.77, \factorsMult, 0.393, \amp, 0.94);
NF('moss').set(\lfnFreq, 0.05, \mod, 2.65, \from, 10.35, \to, 37.32, \freqFrom, 111.43, \freqTo, 1764.67, \jitter, 0.236, \ampStep, 0.167, \duty, 0.514, \hpf, 172.24, \sdm, 47.67, \grainGain, 3.13, \knum, 17.44, \factorsMult, 0.685, \amp, 0.524);
NF('moss').set(\lfnFreq, 1.5, \mod, 6.34, \from, 5.98, \to, 2.15, \freqFrom, 1.87, \freqTo, 391.41, \jitter, 0.041, \ampStep, 0.248, \duty, 0.439, \hpf, 1194.89, \sdm, 6.71, \grainGain, 0.427, \knum, 5.88, \factorsMult, 0.742, \amp, 0.94);
NF('moss').set(\lfnFreq, 11.22, \mod, 8.99, \from, 15.75, \to, 5.06, \freqFrom, 500.0, \freqTo, 2519.47, \jitter, 0.764, \ampStep, 0.208, \duty, 0.719, \hpf, 40.33, \sdm, 3.17, \grainGain, 0.701, \knum, 7.68, \factorsMult, 1.503, \amp, 0.94);
NF('moss').set(\lfnFreq, 0.06, \mod, 133.54, \from, 28.78, \to, 5.49, \freqFrom, 1.0, \freqTo, 129.94, \jitter, 0.596, \ampStep, 0.109, \duty, 0.174, \hpf, 41.93, \sdm, 14.44, \grainGain, 1.003, \knum, 1.67, \factorsMult, 0.241, \amp, 0.94);
NF('moss').set(\lfnFreq, 7.48, \mod, 5.75, \from, 1.9, \to, 2.07, \freqFrom, 1.0, \freqTo, 127.32, \jitter, 0.02, \ampStep, 0.106, \duty, 0.664, \hpf, 25.49, \sdm, 60.0, \grainGain, 0.056, \knum, 7.64, \factorsMult, 1.129, \amp, 0.94);
NF('moss').set(\lfnFreq, 0.13, \mod, 1.78, \from, 1.1, \to, 13.8, \freqFrom, 13.12, \freqTo, 101.39, \jitter, 0.964, \ampStep, 0.621, \duty, 0.099, \hpf, 21.65, \sdm, 45.87, \grainGain, 0.369, \knum, 13.62, \factorsMult, 0.675, \amp, 0.731);


// gorse
NF('gorse').set(\sawFreq, 22.01, \c, 0.97, \delay, 0.03, \b, 0.18, \aa, 1.33, \bb, 29.37, \feedback, 1.0, \peakFreq, 2416.54, \a, 0.75, \amp, 0.02, \hpf, 2078.45);
NF('gorse').set(\sawFreq, 20.78, \c, 0.04, \delay, 0.0, \b, 0.87, \aa, 1.63, \bb, 18.32, \feedback, 1.0, \peakFreq, 527.95, \a, 0.35, \amp, 0.13, \hpf, 433.62);
NF('gorse').set(\sawFreq, 113.01, \c, 0.23, \delay, 0.03, \b, 0.54, \aa, 16.04, \bb, 3.33, \feedback, 0.99, \peakFreq, 1725.9, \a, 0.45, \amp, 0.54, \hpf, 5212.67);
NF('gorse').set(\sawFreq, 123.0, \c, 0.8, \delay, 0.03, \b, 0.3, \aa, 8.53, \bb, 2.53, \feedback, 1.0, \peakFreq, 1100.46, \a, 0.21, \amp, 0.11, \hpf, 3215.49);
NF('gorse').set(\sawFreq, 140.28, \c, 0.13, \delay, 0.01, \b, 0.69, \aa, 6.01, \bb, 6.02, \feedback, 1.0, \peakFreq, 3583.55, \a, 0.17, \amp, 0.7, \hpf, 486.62);
NF('gorse').set(\a, 0.2077, \b, 0.5032, \c, 0.442, \sawFreq, 25.83, \feedback, 0.99247, \delay, 0.0002, \aa, 4.64, \bb, 1.2, \peakFreq, 3987.17, \peakGain, -10.41, \hpf, 90.1, \fbGain, 0.198, \amp, 0.033);
NF('gorse').set(\a, 0.4607, \b, 0.3907, \c, 0.22, \sawFreq, 190.78, \feedback, 0.99212, \delay, 0.0377, \aa, 23.71, \bb, 4.12, \peakFreq, 1033.87, \peakGain, -7.71, \hpf, 6186.46, \fbGain, 0.027, \amp, 0.36);
NF('gorse').set(\a, 0.2946, \b, 0.8753, \c, 0.055, \sawFreq, 22.73, \feedback, 1.0, \delay, 0.0003, \aa, 3.0, \bb, 8.25, \peakFreq, 946.06, \peakGain, -9.3, \hpf, 731.13, \fbGain, 0.085, \amp, 0.533);



// bramble
NF('bramble').set(\sdm, 3.93, \repeats, 2.0, \from, 3.68, \to, 13.86, \mod, 2.58, \rate, 2.66, \trigMin, 13.79, \trigMax, 285.26, \freq, 1204.78, \mf, 0.02, \bw, 1.1, \hpf, 191.38, \amp, 0.335);
NF('bramble').set(\repeats, 11.0, \mf, 0.36, \trigMax, 796.74, \amp, 0.7, \rate, 3.97, \sdm, 1.93, \bw, 3.14, \freq, 464.81, \from, 14.44, \trigMin, 17.16, \to, 7.5, \hpf, 95.53, \mod, 1.55);
NF('bramble').set(\repeats, 10.0, \mf, 0.13, \trigMax, 722.21, \amp, 0.7, \rate, 13.21, \sdm, 6.22, \bw, 10.46, \freq, 563.96, \from, 10.03, \trigMin, 168.56, \to, 54.53, \hpf, 505.92, \mod, 78.19);
NF('bramble').set(\repeats, 12.0, \mf, 0.39, \trigMax, 1348.17, \amp, 0.7, \rate, 14.15, \sdm, 3.34, \bw, 5.67, \freq, 100.0, \from, 1.43, \trigMin, 110.85, \to, 12.52, \hpf, 64.15, \mod, 53.02);
NF('bramble').set(\repeats, 4.0, \mf, 0.14, \trigMax, 329.53, \amp, 0.7, \rate, 0.77, \sdm, 0.28, \bw, 1.27, \freq, 773.75, \from, 3.0, \trigMin, 35.97, \to, 7.81, \hpf, 303.04, \mod, 8.85);
NF('bramble').set(\sdm, 0.289, \repeats, 3.0, \from, 1.7, \to, 2.49, \mod, 1.3, \rate, 60.0, \trigMin, 400.0, \trigMax, 1363.9, \freq, 655.12, \mf, 0.428, \bw, 18.45, \hpf, 24.66, \amp, 0.315);
NF('bramble').set(\sdm, 1.0, \repeats, 2.0, \from, 1.0, \to, 20.0, \mod, 40.0, \rate, 12.0, \trigMin, 40.0, \trigMax, 1000.0, \freq, 1000.0, \mf, 0.3, \bw, 12.0, \hpf, 40.0, \amp, 0.427);
NF('bramble').set(\sdm, 0.676, \repeats, 2.0, \from, 19.74, \to, 2.07, \mod, 53.02, \rate, 2.93, \trigMin, 66.07, \trigMax, 1119.87, \freq, 1468.18, \mf, 1.0, \bw, 1.17, \hpf, 50.86, \amp, 0.7);



// sedge
NF('sedge').set(\surface, 0.416, \lop, 1175.97, \lopVol, 0.126, \hipVol, 0.393, \noiseRate, 49.28, \amp, 0.794, \frequencyB, 0.224, \bsRate, 4.81, \sdm, 10.02, \bsLo, 549.61, \fto, 58.65, \hip, 201.94, \bsHi, 378.65, \ffrom, 2.44, \hpf, 445.27);
NF('sedge').set(\surface, 0.22, \lop, 12557.65, \lopVol, 0.457, \hipVol, 0.463, \noiseRate, 22.75, \amp, 0.794, \frequencyB, 0.506, \bsRate, 0.119, \sdm, 2.27, \bsLo, 795.16, \fto, 18.8, \hip, 106.52, \bsHi, 2299.52, \ffrom, 7.06, \hpf, 46.18);
NF('sedge').set(\surface, 0.196, \lop, 1385.58, \lopVol, 0.56, \hipVol, 0.816, \noiseRate, 200.0, \amp, 0.794, \frequencyB, 0.135, \bsRate, 0.352, \sdm, 1.3, \bsLo, 130.51, \fto, 10.28, \hip, 27.86, \bsHi, 361.24, \ffrom, 10.78, \hpf, 75.3);
NF('sedge').set(\surface, 0.479, \lop, 12858.62, \lopVol, 0.105, \hipVol, 0.516, \noiseRate, 60.56, \amp, 0.794, \frequencyB, 0.431, \bsRate, 1.284, \sdm, 8.15, \bsLo, 304.11, \fto, 263.61, \hip, 55.25, \bsHi, 1159.88, \ffrom, 67.21, \hpf, 351.6);
NF('sedge').set(\surface, 0.637, \lop, 4120.74, \lopVol, 0.725, \hipVol, 0.911, \noiseRate, 26.04, \amp, 0.794, \frequencyB, 0.905, \bsRate, 3.822, \sdm, 4.77, \bsLo, 2894.58, \fto, 184.22, \hip, 32.55, \bsHi, 1426.11, \ffrom, 27.62, \hpf, 65.99);
NF('sedge').set(\surface, 0.917, \lop, 1727.16, \lopVol, 0.577, \hipVol, 0.594, \noiseRate, 15.66, \amp, 0.794, \frequencyB, 0.637, \bsRate, 0.244, \sdm, 3.15, \bsLo, 250.07, \fto, 95.98, \hip, 26.91, \bsHi, 1072.09, \ffrom, 2.74, \hpf, 98.45);
NF('sedge').set(\surface, 0.222, \lop, 1515.35, \lopVol, 0.153, \hipVol, 0.0, \noiseRate, 18.59, \amp, 1.0, \frequencyB, 0.722, \bsRate, 0.06, \sdm, 1.09, \bsLo, 708.56, \fto, 295.15, \hip, 257.0, \bsHi, 201.6, \ffrom, 13.23, \hpf, 94.03);
NF('sedge').set(\sdm, 4.64, \ffrom, 1.36, \fto, 490.1, \noiseRate, 2.17, \bsRate, 0.644, \bsLo, 206.07, \bsHi, 214.33, \frequencyB, 0.973, \surface, 0.165, \lop, 1723.32, \hip, 723.42, \hpf, 1270.15, \lopVol, 0.809, \hipVol, 0.142, \amp, 0.735);



// nettle
NF('nettle').set(\a, 0.712, \filtLo, 7170.86, \wobLo, 813.99, \demGain, 1.46, \b, 0.0, \modFrom, 72.85, \pmFreq, 30.23, \filtHi, 16511.64, \c, 0.738, \hpf, 342.3, \wobHi, 3059.0, \amp, 0.776);
NF('nettle').set(\a, 0.204, \b, 0.095, \c, 0.124, \pmFreq, 1.09, \modFrom, 500.0, \wobLo, 133.17, \wobHi, 419.74, \filtLo, 1024.71, \filtHi, 20000.0, \hpf, 20.81, \demGain, 1.31, \cScale, 306.7, \bScale, 195.17, \filtModScale, 0.01, \lagTime, 0.0015, \gritGain, 0.081, \eqFreqLo, 850.13, \eqFreqHi, 2414.19, \amp, 0.728);
NF('nettle').set(\a, 0.289, \b, 0.161, \c, 0.173, \pmFreq, 1.26, \modFrom, 69.52, \wobLo, 116.58, \wobHi, 203.72, \filtLo, 1186.63, \filtHi, 5173.04, \hpf, 40.51, \demGain, 0.87, \cScale, 107.89, \bScale, 204.9, \filtModScale, 0.051, \lagTime, 0.0012, \gritGain, 1.005, \eqFreqLo, 1538.92, \eqFreqHi, 4172.2, \amp, 0.728);
NF('nettle').set(\a, 0.458, \b, 0.385, \c, 0.139, \pmFreq, 95.42, \modFrom, 23.91, \wobLo, 443.42, \wobHi, 510.27, \filtLo, 1969.59, \filtHi, 14183.72, \hpf, 296.54, \demGain, 1.36, \cScale, 207.59, \bScale, 4496.35, \filtModScale, 0.275, \lagTime, 0.0172, \gritGain, 0.131, \eqFreqLo, 549.6, \eqFreqHi, 6262.39, \amp, 0.978);
NF('nettle').set(\a, 0.91, \b, 0.054, \c, 0.437, \pmFreq, 85.15, \modFrom, 102.46, \wobLo, 1606.67, \wobHi, 540.6, \filtLo, 4147.7, \filtHi, 10866.46, \hpf, 484.79, \demGain, 1.43, \cScale, 796.0, \bScale, 352.93, \filtModScale, 0.149, \lagTime, 0.0138, \gritGain, 0.126, \eqFreqLo, 2245.09, \eqFreqHi, 3947.3, \amp, 0.658);
NF('nettle').set(\a, 0.583, \b, 0.49, \c, 0.534, \pmFreq, 3.07, \modFrom, 65.79, \wobLo, 548.29, \wobHi, 2104.05, \filtLo, 2164.95, \filtHi, 5541.39, \hpf, 126.69, \demGain, 3.02, \cScale, 1375.54, \bScale, 619.78, \filtModScale, 0.142, \lagTime, 0.0112, \gritGain, 0.251, \eqFreqLo, 6388.57, \eqFreqHi, 6729.63, \amp, 0.658);
NF('nettle').set(\a, 0.289, \b, 0.009, \c, 0.103, \pmFreq, 6.81, \modFrom, 24.81, \wobLo, 299.04, \wobHi, 1012.4, \filtLo, 4274.66, \filtHi, 8212.94, \hpf, 69.71, \demGain, 10.09, \cScale, 1826.97, \bScale, 704.43, \filtModScale, 0.03, \lagTime, 0.0263, \gritGain, 0.611, \eqFreqLo, 2143.37, \eqFreqHi, 5201.65, \amp, 0.728);
NF('nettle').set(\a, 0.574, \b, 0.293, \c, 0.064, \pmFreq, 1.02, \modFrom, 29.03, \wobLo, 399.75, \wobHi, 207.02, \filtLo, 1581.23, \filtHi, 5000.73, \hpf, 20.24, \demGain, 0.78, \cScale, 428.52, \bScale, 127.39, \filtModScale, 0.03, \lagTime, 0.0043, \gritGain, 0.786, \eqFreqLo, 545.09, \eqFreqHi, 2739.02, \amp, 0.702);


// clover
Ndef('clover').set(\ser, 263.23, \sdm, 1.673, \step, 2.415, \brownLo, 0.94, \brownHi, 2.41, \mf, 0.01803, \stepsGain, 0.897, \stepsStep, 0.048, \stepsLen, 15.44, \amp, 0.94);
Ndef('clover').set(\ser, 57.37, \sdm, 7.153, \step, 0.115, \brownLo, 1.46, \brownHi, 6.63, \mf, 0.0364, \stepsGain, 0.543, \stepsStep, 0.7691, \stepsLen, 90.82, \amp, 0.885);
Ndef('clover').set(\ser, 905.23, \sdm, 1.252, \step, 7.181, \brownLo, 1.31, \brownHi, 15.55, \mf, 0.02762, \stepsGain, 0.643, \stepsStep, 0.27, \stepsLen, 45.53, \amp, 0.885);
Ndef('clover').set(\ser, 1579.42, \sdm, 3.024, \step, 0.238, \brownLo, 1.52, \brownHi, 17.97, \mf, 0.01689, \stepsGain, 0.804, \stepsStep, 0.0862, \stepsLen, 23.43, \amp, 0.885);
Ndef('clover').set(\ser, 2000.0, \sdm, 0.5, \step, 0.125, \brownLo, 0.55, \brownHi, 16.12, \mf, 0.00141, \stepsGain, 0.0, \stepsStep, 0.0231, \stepsLen, 6.31, \amp, 1.0);
Ndef('clover').set(\ser, 76.36, \sdm, 1.536, \step, 0.109, \brownLo, 0.83, \brownHi, 1.06, \mf, 0.0097, \stepsGain, 0.644, \stepsStep, 0.0162, \stepsLen, 129.75, \amp, 1.0);
Ndef('clover').set(\ser, 79.89, \sdm, 1.026, \step, 1.229, \brownLo, 1.11, \brownHi, 4.67, \mf, 0.0044, \stepsGain, 0.13, \stepsStep, 0.024, \stepsLen, 8.87, \amp, 1.0);
Ndef('clover').set(\ser, 469.97, \sdm, 3.179, \step, 8.066, \brownLo, 0.83, \brownHi, 15.34, \mf, 0.00489, \stepsGain, 1.0, \stepsStep, 0.2007, \stepsLen, 160.0, \amp, 1.0);

// yarrow
Ndef('yarrow').set(\fspeed, 20.0, \fcenter, 200.0, \sdm, 0.1, \mfreq, 0.01, \filtBw, 6.0, \modFreq, 5.0, \harms, 120.0, \drive, 10.0, \bsRate, 5.0, \bsLo, 100.0, \bsHi, 8000.0, \lpf, 12000.0, \hpf, 30.0, \amp, 0.957);
Ndef('yarrow').set(\fspeed, 94.12, \fcenter, 477.33, \sdm, 0.839, \mfreq, 0.3162, \filtBw, 25.02, \modFreq, 20.81, \harms, 381.05, \drive, 32.94, \bsRate, 5.0, \bsLo, 100.0, \bsHi, 8000.0, \lpf, 12000.0, \hpf, 30.0, \amp, 0.957);
Ndef('yarrow').set(\fspeed, 83.73, \fcenter, 808.86, \sdm, 1.797, \mfreq, 0.2482, \filtBw, 13.55, \modFreq, 7.44, \harms, 237.82, \drive, 37.71, \bsRate, 2.77, \bsLo, 112.72, \bsHi, 6061.26, \lpf, 12670.93, \hpf, 47.87, \amp, 0.957);
Ndef('yarrow').set(\fspeed, 54.11, \fcenter, 1004.34, \sdm, 1.307, \mfreq, 0.1031, \filtBw, 10.88, \modFreq, 4.77, \harms, 179.42, \drive, 33.52, \bsRate, 2.14, \bsLo, 128.71, \bsHi, 5342.67, \lpf, 10120.88, \hpf, 39.57, \amp, 0.957);
Ndef('yarrow').set(\fspeed, 69.49, \fcenter, 891.13, \sdm, 1.747, \mfreq, 0.0139, \filtBw, 6.86, \modFreq, 12.71, \harms, 85.44, \drive, 20.77, \bsRate, 4.42, \bsLo, 103.74, \bsHi, 5566.11, \lpf, 17784.49, \hpf, 24.68, \amp, 0.957);
Ndef('yarrow').set(\fspeed, 5.88, \fcenter, 195.2, \sdm, 0.02, \mfreq, 0.1949, \filtBw, 4.04, \modFreq, 8.01, \harms, 16.22, \drive, 2.07, \bsRate, 1.36, \bsLo, 777.18, \bsHi, 1956.45, \lpf, 11873.51, \hpf, 38.79, \amp, 0.7);
Ndef('yarrow').set(\fspeed, 84.65, \fcenter, 362.0, \sdm, 0.918, \mfreq, 0.526, \filtBw, 19.48, \modFreq, 17.38, \harms, 353.66, \drive, 32.13, \bsRate, 5.27, \bsLo, 73.19, \bsHi, 8033.66, \lpf, 10240.52, \hpf, 21.08, \amp, 0.957);
Ndef('yarrow').set(\fspeed, 17.73, \fcenter, 154.63, \sdm, 1.931, \mfreq, 0.6961, \filtBw, 8.49, \modFreq, 4.31, \harms, 58.0, \drive, 8.21, \bsRate, 15.53, \bsLo, 255.59, \bsHi, 1215.41, \lpf, 7179.78, \hpf, 23.36, \amp, 0.957);

// teasel
NF('teasel').set(\modRate, 9.01, \modFrom, 100.0, \modTo, 10070.0, \peakFreq, 400.0, \lpf, 1070.0, \hpf, 30.0, \carrier, 1.0, \sdm, 40.0, \gateRate, 1.0, \sparkleGain, 0.4, \demGain, 2.0, \amp, 0.808);
NF('teasel').set(\modRate, 69.37, \modFrom, 156.09, \modTo, 5599.27, \peakFreq, 2853.7, \lpf, 1001.49, \hpf, 28.63, \carrier, 2.85, \sdm, 30.46, \gateRate, 9.98, \sparkleGain, 0.173, \demGain, 1.15, \amp, 0.899);
NF('teasel').set(\modRate, 2.53, \modFrom, 1198.73, \modTo, 594.29, \peakFreq, 508.45, \lpf, 2595.68, \hpf, 55.07, \carrier, 59.46, \sdm, 0.46, \gateRate, 5.45, \sparkleGain, 0.241, \demGain, 1.41, \amp, 0.524);
NF('teasel').set(\modRate, 5.26, \modFrom, 972.6, \modTo, 798.39, \peakFreq, 601.56, \lpf, 1699.5, \hpf, 50.87, \carrier, 121.19, \sdm, 0.67, \gateRate, 9.08, \sparkleGain, 0.251, \demGain, 1.36, \amp, 0.754);
NF('teasel').set(\modRate, 10.94, \modFrom, 11.48, \modTo, 14670.43, \peakFreq, 788.23, \lpf, 2768.71, \hpf, 426.42, \carrier, 1.77, \sdm, 5.6, \gateRate, 1.46, \sparkleGain, 0.947, \demGain, 6.88, \amp, 0.227);
NF('teasel').set(\modRate, 0.86, \modFrom, 952.58, \modTo, 1687.09, \peakFreq, 626.53, \lpf, 5822.48, \hpf, 427.32, \carrier, 0.54, \sdm, 2.62, \gateRate, 10.91, \sparkleGain, 0.298, \demGain, 0.96, \amp, 0.512);
NF('teasel').set(\modRate, 71.98, \modFrom, 132.0, \modTo, 2217.9, \peakFreq, 387.69, \lpf, 482.05, \hpf, 1080.12, \carrier, 3.15, \sdm, 0.07, \gateRate, 3.24, \sparkleGain, 1.128, \demGain, 12.36, \amp, 0.39);
NF('teasel').set(\modRate, 69.58, \modFrom, 342.89, \modTo, 702.38, \peakFreq, 577.32, \lpf, 270.7, \hpf, 53.8, \carrier, 8.34, \sdm, 0.53, \gateRate, 3.68, \sparkleGain, 0.738, \demGain, 0.49, \amp, 0.474);


