// gorse
NF('gorse').set(\a, 0.75, \b, 0.18, \c, 0.97, \sawFreq, 22.01, \feedback, 1.0, \delay, 0.03, \aa, 1.33, \bb, 29.37, \peakFreq, 2416.54, \hpf, 2078.45, \amp, 0.02);
NF('gorse').set(\a, 0.35, \b, 0.87, \c, 0.04, \sawFreq, 20.78, \feedback, 1.0, \delay, 0.0, \aa, 1.63, \bb, 18.32, \peakFreq, 527.95, \hpf, 433.62, \amp, 0.13);
NF('gorse').set(\a, 0.45, \b, 0.54, \c, 0.23, \sawFreq, 113.01, \feedback, 0.99, \delay, 0.03, \aa, 16.04, \bb, 3.33, \peakFreq, 1725.9, \hpf, 5212.67, \amp, 0.54);
NF('gorse').set(\a, 0.21, \b, 0.3, \c, 0.8, \sawFreq, 123.0, \feedback, 1.0, \delay, 0.03, \aa, 8.53, \bb, 2.53, \peakFreq, 1100.46, \hpf, 3215.49, \amp, 0.11);
NF('gorse').set(\a, 0.17, \b, 0.69, \c, 0.13, \sawFreq, 140.28, \feedback, 1.0, \delay, 0.01, \aa, 6.01, \bb, 6.02, \peakFreq, 3583.55, \hpf, 486.62, \amp, 0.7);

// bramble
NF('bramble').set(\sdm, 3.93, \repeats, 2.0, \from, 3.68, \to, 13.86, \mod, 2.58, \rate, 2.66, \trigMin, 13.79, \trigMax, 285.26, \freq, 1204.78, \mf, 0.02, \bw, 1.1, \hpf, 191.38, \amp, 0.7);
NF('bramble').set(\sdm, 1.93, \repeats, 11.0, \from, 14.44, \to, 7.5, \mod, 1.55, \rate, 3.97, \trigMin, 17.16, \trigMax, 796.74, \freq, 464.81, \mf, 0.36, \bw, 3.14, \hpf, 95.53, \amp, 0.7);
NF('bramble').set(\sdm, 6.22, \repeats, 10.0, \from, 10.03, \to, 54.53, \mod, 78.19, \rate, 13.21, \trigMin, 168.56, \trigMax, 722.21, \freq, 563.96, \mf, 0.13, \bw, 10.46, \hpf, 505.92, \amp, 0.7);
NF('bramble').set(\sdm, 3.34, \repeats, 12.0, \from, 1.43, \to, 12.52, \mod, 53.02, \rate, 14.15, \trigMin, 110.85, \trigMax, 1348.17, \freq, 100.0, \mf, 0.39, \bw, 5.67, \hpf, 64.15, \amp, 0.7);
NF('bramble').set(\sdm, 0.28, \repeats, 4.0, \from, 3.0, \to, 7.81, \mod, 8.85, \rate, 0.77, \trigMin, 35.97, \trigMax, 329.53, \freq, 773.75, \mf, 0.14, \bw, 1.27, \hpf, 303.04, \amp, 0.7);

/*

Not ready

teasel
NF('teasel').set(\modRate, 6.06, \modFrom, 664.29, \modTo, 6694.05, \peakFreq, 937.54, \lpf, 312.22, \hpf, 119.4, \sparkleGain, 0.87, \demGain, 6.65, \amp, 0.52);

yarrow
Ndef('yarrow').set(\fspeed, 7.46, \fcenter, 1105.99, \sdm, 0.2, \mfreq, 0.0, \filtBw, 24.88, \modFreq, 16.94, \harms, 88.42, \drive, 3.0, \bsRate, 1.66, \bsLo, 549.39, \bsHi, 1871.54, \lpf, 6711.87, \hpf, 62.9, \amp, 0.87);

*/
